// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	handler "github.com/huangwei021230/api-gateway/hertz-server/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.POST("/gateway/:service/:method", handler.FindServiceAndCall)
	routeInfo := r.Routes()
	hlog.Info(routeInfo)
}
