// Code generated by Kitex v0.6.1. DO NOT EDIT.
package additionmanagement

import (
	server "github.com/cloudwego/kitex/server"
	management "github.com/huangwei021230/api-gateway/microservices/addition-service/kitex_gen/addition/management"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler management.AdditionManagement, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
