// Code generated by Kitex v0.6.1. DO NOT EDIT.
package gateway

import (
	server "github.com/cloudwego/kitex/server"
	api "github.com/huangwei021230/api-gateway/hertz-http-server/kitex_gen/api"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler api.Gateway, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
