// Code generated by hertz generator.

package gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listallserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchforserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}
